name = "Amigos"
author = "aMerryElk"
version = "3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f67784915f0dd52896a30633a38c878a424a173d85baa6e38cb5ec57f4c624c9"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
